# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00708ac72a0a8a46c4568e4ecaf717984a8ba18cce32c12b07f3d5899a9528af130f91b5294f7e6c3433f8b8bef4df70ddcb11d0fb598e9e761dee2935d5bbff

test:
  secret_key_base: 5445ebee8ae036a370987ede65908ed5840543239e880e5ef65c20cb254d966251c366480c982165dce51b9cc720c070c6a1e986e9612cbc3d32f216dc26155d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
